version: "3"

services:
  minio:
    container_name: minio
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopassword
    image: minio/minio:latest
    ports:
      - "9001:9001"
      - "9000:9000"
    entrypoint: sh
    command: '-c ''mkdir -p /minio_data/starrocks && minio server /minio_data --console-address ":9001"'''
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio_mc:
    # This service is short lived, it does this:
    # - starts up
    # - checks to see if the MinIO service `minio` is ready
    # - creates a MinIO Access Key that the StarRocks services will use
    # - exits
    image: minio/mc:latest
    entrypoint:
      - sh
      - -c
      - |
        until mc ls minio > /dev/null 2>&1; do
          sleep 0.5
        done

        mc alias set myminio http://minio:9000 miniouser miniopassword
        mc admin user svcacct add --access-key AAAAAAAAAAAAAAAAAAAA \
        --secret-key BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB \
        myminio \
        miniouser
    depends_on:
      - minio

  starrocks-fe:
    build:
      context: .
      dockerfile: ./DockerFile_FrontEnd
    hostname: starrocks-fe
    container_name: starrocks-fe
    user: root
    environment:
      - STARROCKS_HOME=/starrocks/fe1
      - HTTP_PORT=8031
      - THRIFT_RPC_PORT=9021
      - SQL_QUERY_PORT=9031
      - EDIT_LOG_PORT=9011
      - MINIO_URL=http://minio:9000
      - MINIO_BUCKET=starrocks
      - MINIO_ACCESS_KEY=AAAAAAAAAAAAAAAAAAAA
      - MINIO_SECRET_KEY=BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    ports:
      - 8031:8031
      - 9021:9021
      - 9031:9031
    volumes:
      - ./cdr/cdm/starrocks:/starrocks
    healthcheck:
      test: 'mysql -u root -h starrocks-fe -P 9031 -e "show frontends\G" |grep "Alive: true"'
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - minio

  starrocks-cn:
    image: starrocks/cn-ubuntu:3.2-latest
    command:
      - /bin/bash
      - -c
      - |
        sleep 15s;
        ulimit -u 65535;
        ulimit -n 65535;
        mysql --connect-timeout 2 -h starrocks-fe -P9031 -uroot -e "ALTER SYSTEM ADD COMPUTE NODE \"starrocks-cn:9050\";"
        /opt/starrocks/cn/bin/start_cn.sh
    ports:
      - 8040:8040
    hostname: starrocks-cn
    container_name: starrocks-cn
    user: root
    depends_on:
      - starrocks-fe
      - minio
    healthcheck:
      test: 'mysql -u root -h starrocks-fe -P 9031 -e "SHOW COMPUTE NODES\G" |grep "Alive: true"'
      interval: 10s
      timeout: 5s
      retries: 3
