FROM starrocks/cn-ubuntu:3.2.8

RUN mkdir -p /opt/sr_scripts

COPY scripts/* /opt/sr_scripts

RUN chmod a+x /opt/sr_scripts/*

RUN /opt/sr_scripts/cn-setup.sh

ENTRYPOINT ["/opt/sr_scripts/cn-entrypoint.sh"]
