name: Build & Push StarRocks CN Image to GHCR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

  push:
    branches:
      - main
      - master
      - develop

jobs:
  trigger-build-push:
    uses: ./.github/workflows/build_push_node_images.yaml
    with:
      node_name: cn
      docker_file: './DockerFile_ComputeNode'
    secrets: inherit
