name: Build & Push StarRocks Node to GHCR

on:
  workflow_call:
    inputs:
      node_name:
        description: 'Name of the node to build and push, e.g. fe or cn'
        required: true
        type: string
      docker_file:
        description: 'Path to the docker file'
        required: true
        type: string

jobs:
  build-push-tool-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: '${{ secrets.GHCR_USERNAME }}'
          password: '${{ secrets.GHCR_TOKEN }}'

      - name: Build and push node images
        id: build-and-push
        run: |
          dockerfile=${{ inputs.docker_file }}
          tag="ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}:${{inputs.node_name}}-pr-${{ github.event.number }}"

          echo "Building and pushing ${{ inputs.node_name }} image..."
          echo "tagging image with $tag"

          docker buildx build --file "$dockerfile" --tag "$tag" \
            --build-arg "BUILD_DATE=${{ steps.date.outputs.date }}" \
            --build-arg "VCS_REF=${{ github.sha }}" \
            --build-arg "BRANCH=${{ github.ref }}" \
            --build-arg "TAG=${{ github.ref }}" \
            --push .
